### ISSUE TITLE
相手が現れなかったり、相手の手が遅いとルームを消して別のルームを作成してしまう

### ISSUE THREAD

**Issue by magcho** [Goyotan/othello_bot#2]
## 症状
- 始まっていない試合のルームを5秒くらいで勝手に消して別の部屋を作ってしまう。
- 実行中の試合で相手の思考時間が約5秒以上かかると反則手でルームが強制終了する。

##  原因
Play.py内で相手の手などを取得するapiへのアクセスにおいて5秒でタイムアウトが発生するが、タムアウト時にPlay.pyの挙動が怪しい？？

## 対応
とりあえずPlay.pyを修正した物をPRしておくので見てくれ。

**Comment by Goyotan** [comment]
# 対応.1
このscriptはあくまで追加パッケージという気持ちで開発したのでベースプログラムへのパッチは本家
https://github.com/KousukeIshii/OthelloArenaPython/
へ投げるべきではないかと思う．

# 対応.2
こちらが本家のフォークをし，そこへbot scriptを追加していく本家improvementスタイルでいくか．

どちらにしよう． @magcho

**Comment by magcho** [comment]
forkして`Playmod.py`とかにしておいて、main.py内で`import Playmod`するとか？

ちゃんと検証してないし、普通に使ってる分にはPlay.pyは問題ないから本家にPRしなくてもいいかなという気持ち

**Comment by Goyotan** [comment]
残されている期間的に面倒くさいので対応はしません🐾
代わりに一句詠みます．

オセロとは
無償の愛の
何かかな
